FROM $DOCKER_IMAGE
ARG VERSION

RUN apk add --no-cache git gcc musl-dev make

WORKDIR /go/src/github.com/golang-migrate/migrate

ENV GO111MODULE=on
ENV COVERAGE_DIR=/tmp/coverage

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

CMD ["make" "test"]
